// Section 1.7: the limits, elements and subnormal numbers of F(2, 3, -1, 1), plus a
// plot of F and of the extended F. The LaTeX tables written to out/ are the ones
// report.tex includes, so the report shows what this program actually computed.
#include "na/common.hpp"
#include "na/fpn.hpp"

#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {

const na::FpnSystem kSystem{2, 3, -1, 1};

// 17 significant digits, so values such as 0.625 print exactly.
std::string decimal(double x) {
    std::ostringstream out;
    out << std::setprecision(17) << x;
    return out.str();
}

// Rows of "value, significand" for a list of positive numbers.
std::vector<na::Row> element_rows(const std::vector<na::Fpn>& positive) {
    std::vector<na::Row> rows;
    for (const na::Fpn& x : positive) {
        rows.push_back({decimal(x.value(kSystem)), x.latex(kSystem)});
    }
    return rows;
}

// A complete tabular environment, so report.tex can \input the file as it stands.
void write_tabular(const std::string& path, const std::vector<std::string>& header,
                   const std::vector<na::Row>& rows) {
    std::ofstream out(path);
    out << "% Generated by hw1/main.cpp -- do not edit by hand.\n";
    out << "\\begin{tabular}{" << std::string(header.size(), 'c') << "}\n";
    out << "\\hline\n";
    for (std::size_t i = 0; i < header.size(); ++i) {
        out << (i == 0 ? "" : " & ") << header[i];
    }
    out << " \\\\\n\\hline\n";
    na::print_table(out, header, rows, na::TableStyle::LaTeX);
    out << "\\hline\n\\end{tabular}\n";
}

// Ticks on the real axis. With include_subnormals the numbers added by
// Definition 1.15 are drawn in blue.
void write_plot(const std::string& path, bool include_subnormals) {
    std::ofstream out(path);
    out << "% Generated by hw1/main.cpp -- do not edit by hand.\n";
    out << "\\begin{tikzpicture}[xscale=1.9, yscale=0.8]\n";
    out << "  \\draw[thick,<->] (-3.9,0) -- (3.9,0);\n";
    out << "  % elements of F\n";
    for (const na::Fpn& x : na::normalized(kSystem)) {
        const double v = x.value(kSystem);
        out << "  \\draw[red] (" << v << ",0.18) -- (" << v << ",-0.18);\n";
        out << "  \\draw[red] (" << -v << ",0.18) -- (" << -v << ",-0.18);\n";
    }
    if (include_subnormals) {
        out << "  % subnormal numbers (Definition 1.15)\n";
        for (const na::Fpn& x : na::subnormals(kSystem)) {
            const double v = x.value(kSystem);
            out << "  \\draw[blue] (" << v << ",0.18) -- (" << v << ",-0.18);\n";
            out << "  \\draw[blue] (" << -v << ",0.18) -- (" << -v << ",-0.18);\n";
        }
    }
    out << "  % axis labels\n";
    for (int k = -3; k <= 3; ++k) {
        out << "  \\node[below] at (" << k << ",-0.25) {$" << k << "$};\n";
    }
    out << "\\end{tikzpicture}\n";
}

} // namespace

int main() {
    namespace fs = std::filesystem;
    const fs::path out_dir = fs::path(NA_SOURCE_DIR) / "out";
    fs::create_directories(out_dir);
    const auto out_path = [&out_dir](const std::string& name) { return (out_dir / name).string(); };

    std::cout << kSystem.describe() << '\n';

    std::cout << "\n[1] the limits of F (Definition 1.19)\n";
    std::cout << "    UFL(F) = beta^L                   = " << decimal(kSystem.ufl()) << '\n';
    std::cout << "    OFL(F) = beta^U (beta - beta^(1-p)) = " << decimal(kSystem.ofl()) << '\n';
    std::cout << "    eps_M  = beta^(1-p)               = " << decimal(kSystem.machine_precision())
              << '\n';
    std::cout << "    eps_u  = eps_M / 2                = " << decimal(kSystem.unit_roundoff())
              << '\n';

    const std::vector<na::Fpn> norm = na::normalized(kSystem);
    const long long enumerated = 2 * static_cast<long long>(norm.size()) + 1;
    std::cout << "\n[2] the elements of F\n";
    na::print_table({"value", "significand"}, element_rows(norm));
    std::cout << "    the positive elements number " << norm.size()
              << "; with both signs and zero, " << enumerated << '\n';
    std::cout << "    Corollary 1.21: #F = 2^p (U - L + 1) + 1 = 2^" << kSystem.p << " x ("
              << kSystem.U << " - (" << kSystem.L << ") + 1) + 1 = " << kSystem.cardinality()
              << '\n';
    std::cout << "    check: "
              << (enumerated == kSystem.cardinality() ? "the enumeration agrees" : "MISMATCH")
              << '\n';

    write_plot(out_path("plot_F.tex"), false);
    std::cout << "\n[3] wrote " << out_path("plot_F.tex") << " (F on the real axis)\n";

    const std::vector<na::Fpn> sub = na::subnormals(kSystem);
    const long long expected_sub = static_cast<long long>(kSystem.power(kSystem.p - 1)) - 1;
    std::cout << "\n[4] the subnormal numbers of F (Definition 1.15)\n";
    na::print_table({"value", "significand"}, element_rows(sub));
    std::cout << "    the positive subnormals number " << sub.size()
              << "; beta^(p-1) - 1 = " << expected_sub << '\n';

    write_plot(out_path("plot_extended.tex"), true);
    std::cout << "\n[5] wrote " << out_path("plot_extended.tex")
              << " (the extended F on the real axis)\n";
    std::cout << "    the extended F has " << enumerated + 2 * static_cast<long long>(sub.size())
              << " elements including zero\n";

    write_tabular(out_path("elements.tex"), {"值", "规格化形式"}, element_rows(norm));
    write_tabular(out_path("subnormal.tex"), {"值", "形式"}, element_rows(sub));
    std::cout << "\n[6] wrote " << out_path("elements.tex") << " and " << out_path("subnormal.tex")
              << '\n';
    return 0;
}
